### ISSUE TITLE
Does this do the same thing as yourls-abusedesk?

### ISSUE THREAD

**Issue by balloontwister** [YOURLS/google-safe-browsing#1]
Sorry for the noobie question . . . 
My yourls is getting a ton of spam (even with a captcha on the front-end). Does this plugin do the same thing as abusedesk from https://code.obsimref.com/projects/yourls-abusedesk -- they both use Google Safe Browsing, but I can't tell if they are using it for the same thing.

**Comment by ozh** [comment]
I don't know about this plugin (4 or 5 clicks on the URL you mention still didn't show up any code, I gave up) but one thing is sure: if you're getting tons of spam with a captcha, then it's fairly certain that the spam doesn't come through your public interface front-end. Check wiki page about Spam on YOURLS project.
