### ISSUE TITLE
Turndown of Legacy Google Safe Browsing APIs

### ISSUE THREAD

**Issue by Zitt** [YOURLS/google-safe-browsing#5]
Got a message from Google on the 8th which said:

> Coupled with the announcement of v4 of the API, we also announced the eventual deprecation of legacy Safe Browsing APIs, v2 and v3 (listed as "Safe Browsing API (Legacy)" in the Google Developer Console). You are receiving this email because you own a Google Developer Project that has activated one of these APIs, which will be turned down October 1st, 2018. All v2 and v3 clients must transition to the v4 API prior to this date. 

Are there any plans to update this plugin to support V4 prior to 10/1/18?

**Comment by alexvf** [comment]
+1

**Comment by ozh** [comment]
This plugin is [supposed to work with V4](https://github.com/YOURLS/google-safe-browsing/pull/7)

**Comment by ozh** [comment]
Confirmed and there are now unit tests to check future smoothness of things
