### ISSUE TITLE
Safe browsing not working

### ISSUE THREAD

**Issue by gfvh** [YOURLS/google-safe-browsing#6]
I tried to post topic on discourse but i added url for testing safe browsing and now akismet blocks me so i will try in here post.

My issue is that i installed safe browsing plugin and it does not trigger. It is activated and API key inserted like needed but when i insert URL what is in safe browsing blacklist then no 403 error message. Can you please test it on your env and see if it does work for you?

env:

llighttpd
php 7.3.13
yourls 1.7.4
freebsd 12.1 p1

website: https://shareurl.it

* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Comment by ozh** [comment]
This plugin is 6 years old, the Safe Browsing API has surely evolved. I think it's using the V3 and I read on https://developers.google.com/safe-browsing that it's now V4.

I'm adding to the readme that this plugin is deprecated and in need of someone sending a pull request to update it :)
